In [1]:
from sklearn.datasets import make_classification
from sklearn.datasets import make_blobs
from sklearn.cluster import SpectralClustering
import matplotlib.pyplot as plt
import pandas as pd
import os
import numpy as np
import math
from scipy import stats
import random
from scipy import stats
from neurocombat_sklearn import CombatModel
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
from sklearn.cluster import KMeans
from random import random
import pickle

## 1. Scenario 1
### Base dataset with same site data

In [62]:
X_base = np.asarray([[ 2    , 2  , 4 ,  8],
                     [ 2    , 2  , 4 ,  8],
                     [ 2    , 2  , 4 ,  8],
                     [ 1    , 2  , 4 ,  8],
                     [ 1    , 2  , 4 ,  8],
                     [ 1    , 2  , 4 ,  8],
                     [ 2    , 2  , 4 ,  8],
                     [ 2    , 2  , 4 ,  8],
                     [ 2    , 2  , 4 ,  8],
                     [ 4    , 2  , 4 ,  8],
                     [ 4    , 2  , 4 ,  8],
                     [ 4    , 2  , 4 ,  8]])

############################# site ####################################

sites = np.asarray([1,1,1,1,1,1,2,2,2,2,2,2]).reshape(-1,1)

############################# age #####################################

ages = np.asarray([5,5,5,5,5,5,5,5,5,5,5,5]).reshape(-1,1)

############################# sex #####################################

sex = np.asarray([1,1,1,1,1,1,1,1,1,1,1,1]).reshape(-1,1)

#######################################################################
site_age_sex = np.concatenate((sites, ages, sex),axis=1)
print("Base dataset:\n feat1 feat2 feat3 feat4 site ages sex \n", np.concatenate((X_base, site_age_sex),axis=1))

# Creating model
model = CombatModel()
# Fitting the model and transforming the training set
X_train_harmonized = model.fit_transform(X_base, sites, sex, ages)
print("\nHarmonized: \n", X_train_harmonized)

# mean along the axis = 1  
print("\nmean of base data: \n", np.mean(X_base, axis = 0)) 
print("mean of base data, 0 - 4 : \n", np.mean(X_base[:5], axis = 0)) 
print("mean of base data, 5 - 9 : \n", np.mean(X_base[5:], axis = 0)) 
# mean along the axis = 1  
print("mean of harmonized data: \n", np.mean(X_train_harmonized, axis = 0))
print("mean of harmonized data: \n", np.mean(X_train_harmonized[0:5], axis = 0))
print("mean of harmonized data: \n", np.mean(X_train_harmonized[5:10], axis = 0))

Base dataset:
 feat1 feat2 feat3 feat4 site ages sex 
 [[2 2 4 8 1 5 1]
 [2 2 4 8 1 5 1]
 [2 2 4 8 1 5 1]
 [1 2 4 8 1 5 1]
 [1 2 4 8 1 5 1]
 [1 2 4 8 1 5 1]
 [2 2 4 8 2 5 1]
 [2 2 4 8 2 5 1]
 [2 2 4 8 2 5 1]
 [4 2 4 8 2 5 1]
 [4 2 4 8 2 5 1]
 [4 2 4 8 2 5 1]]

Harmonized: 
 [[ 5.40491738  1.96933489  3.93866979  7.87733958]
 [ 5.40491738  1.96933489  3.93866979  7.87733958]
 [ 5.40491738  1.96933489  3.93866979  7.87733958]
 [-3.02559509  1.96933489  3.93866979  7.87733958]
 [-3.02559509  1.96933489  3.93866979  7.87733958]
 [-3.02559509  1.96933489  3.93866979  7.87733958]
 [-0.87572318  1.69161333  3.38322666  6.76645331]
 [-0.87572318  1.69161333  3.38322666  6.76645331]
 [-0.87572318  1.69161333  3.38322666  6.76645331]
 [ 7.44190438  1.69161333  3.38322666  6.76645331]
 [ 7.44190438  1.69161333  3.38322666  6.76645331]
 [ 7.44190438  1.69161333  3.38322666  6.76645331]]

mean of base data: 
 [2.25 2.   4.   8.  ]
mean of base data, 0 - 4 : 
 [1.6 2.  4.  8. ]
mean of base data, 5 

I:\Anaconda3\lib\site-packages\neurocombat_sklearn\neurocombat_sklearn.py:348: RuntimeWarning: divide by zero encountered in true_divide
  (abs(delta_hat_new - delta_hat_old) / delta_hat_old).max())


## 2. Scenario 2
### Base dataset with same site data

In [66]:
X_base = np.asarray([[ 2    , 2  , 4 ,  8],
                     [ 2    , 2  , 4 ,  8],
                     [ 2    , 2  , 4 ,  8],
                     [ 1    , 2  , 4 ,  8],
                     [ 1    , 2  , 4 ,  8],
                     [ 1    , 2  , 4 ,  8],
                     [ 4    , 4  , 8 ,  16],
                     [ 4    , 4  , 8 ,  16],
                     [ 4    , 4  , 8 ,  16],
                     [ 2    , 4  , 8 ,  16],
                     [ 2    , 4  , 8 ,  16],
                     [ 2    , 4  , 8 ,  16]])

############################# site ####################################

sites = np.asarray([1,1,1,1,1,1,2,2,2,2,2,2]).reshape(-1,1)

############################# age #####################################

ages = np.asarray([5,5,5,5,5,5,5,5,5,5,5,5]).reshape(-1,1)

############################# sex #####################################

sex = np.asarray([1,1,1,1,1,1,1,1,1,1,1,1]).reshape(-1,1)

#######################################################################
site_age_sex = np.concatenate((sites, ages, sex),axis=1)
print("Base dataset:\n feat1 feat2 feat3 feat4 site ages sex \n", np.concatenate((X_base, site_age_sex),axis=1))

# Creating model
model = CombatModel()
# Fitting the model and transforming the training set
X_train_harmonized = model.fit_transform(X_base, sites, sex, ages)
print("\nHarmonized: \n", X_train_harmonized)

# mean along the axis = 1  
print("\nmean of base data: \n", np.mean(X_base, axis = 0)) 
print("mean of base data, 0 - 4 : \n", np.mean(X_base[:5], axis = 0)) 
print("mean of base data, 5 - 9 : \n", np.mean(X_base[5:], axis = 0)) 
# mean along the axis = 1  
print("mean of harmonized data: \n", np.mean(X_train_harmonized, axis = 0))
print("mean of harmonized data: \n", np.mean(X_train_harmonized[0:5], axis = 0))
print("mean of harmonized data: \n", np.mean(X_train_harmonized[5:10], axis = 0))

Base dataset:
 feat1 feat2 feat3 feat4 site ages sex 
 [[ 2  2  4  8  1  5  1]
 [ 2  2  4  8  1  5  1]
 [ 2  2  4  8  1  5  1]
 [ 1  2  4  8  1  5  1]
 [ 1  2  4  8  1  5  1]
 [ 1  2  4  8  1  5  1]
 [ 4  4  8 16  2  5  1]
 [ 4  4  8 16  2  5  1]
 [ 4  4  8 16  2  5  1]
 [ 2  4  8 16  2  5  1]
 [ 2  4  8 16  2  5  1]
 [ 2  4  8 16  2  5  1]]

Harmonized: 
 [[ 6.4983389   2.70121937  5.40243874 10.80487749]
 [ 6.4983389   2.70121937  5.40243874 10.80487749]
 [ 6.4983389   2.70121937  5.40243874 10.80487749]
 [-2.10716305  2.70121937  5.40243874 10.80487749]
 [-2.10716305  2.70121937  5.40243874 10.80487749]
 [-2.10716305  2.70121937  5.40243874 10.80487749]
 [ 6.34943651  2.89428482  5.78856964 11.57713929]
 [ 6.34943651  2.89428482  5.78856964 11.57713929]
 [ 6.34943651  2.89428482  5.78856964 11.57713929]
 [-2.25677975  2.89428482  5.78856964 11.57713929]
 [-2.25677975  2.89428482  5.78856964 11.57713929]
 [-2.25677975  2.89428482  5.78856964 11.57713929]]

mean of base data: 
 [ 2.25

I:\Anaconda3\lib\site-packages\neurocombat_sklearn\neurocombat_sklearn.py:348: RuntimeWarning: divide by zero encountered in true_divide
  (abs(delta_hat_new - delta_hat_old) / delta_hat_old).max())


## Scenario 3
### Base Dataset

In [71]:
X_base = np.asarray([[ 2    , 2  , 4 ,  8],
                     [ 2    , 2  , 4 ,  8],
                     [ 2    , 2  , 4 ,  8],
                     [ 1    , 2  , 4 ,  8],
                     [ 1    , 2  , 4 ,  8],
                     [ 1    , 2  , 4 ,  8],
                     [ 4    , 4  , 8 ,  16],
                     [ 4    , 4  , 8 ,  16],
                     [ 4    , 4  , 8 ,  16],
                     [ 2    , 4  , 8 ,  16],
                     [ 2    , 4  , 8 ,  16],
                     [ 2    , 4  , 8 ,  16]])

############################# site ####################################

sites = np.asarray([2,2,2,2,2,2,1,1,1,1,1,1]).reshape(-1,1)

############################# age #####################################

ages = np.asarray([1,1,1,2,2,2,1,1,1,2,2,2]).reshape(-1,1)

############################# sex #####################################

sex = np.asarray([1,1,1,1,1,1,1,1,1,1,1,1]).reshape(-1,1)

#######################################################################
site_age_sex = np.concatenate((sites, ages, sex),axis=1)
print("Base dataset:\n feat1 feat2 feat3 feat4 site ages sex \n", np.concatenate((X_base, site_age_sex),axis=1))

# Creating model
model = CombatModel()
# Fitting the model and transforming the training set
X_train_harmonized = model.fit_transform(X_base, sites, sex, ages)
print("\nHarmonized: \n", X_train_harmonized)

# mean along the axis = 1  
print("\nmean of base data: \n", np.mean(X_base, axis = 0)) 
print("mean of base data, 0 - 4 : \n", np.mean(X_base[:5], axis = 0)) 
print("mean of base data, 5 - 9 : \n", np.mean(X_base[5:], axis = 0)) 
# mean along the axis = 1  
print("mean of harmonized data: \n", np.mean(X_train_harmonized, axis = 0))
print("mean of harmonized data: \n", np.mean(X_train_harmonized[0:5], axis = 0))
print("mean of harmonized data: \n", np.mean(X_train_harmonized[5:10], axis = 0))

Base dataset:
 feat1 feat2 feat3 feat4 site ages sex 
 [[ 2  2  4  8  2  1  1]
 [ 2  2  4  8  2  1  1]
 [ 2  2  4  8  2  1  1]
 [ 1  2  4  8  2  2  1]
 [ 1  2  4  8  2  2  1]
 [ 1  2  4  8  2  2  1]
 [ 4  4  8 16  1  1  1]
 [ 4  4  8 16  1  1  1]
 [ 4  4  8 16  1  1  1]
 [ 2  4  8 16  1  2  1]
 [ 2  4  8 16  1  2  1]
 [ 2  4  8 16  1  2  1]]

Harmonized: 
 [[ 2.71958313  3.          6.         12.        ]
 [ 2.71958313  3.          6.         12.        ]
 [ 2.71958313  3.          6.         12.        ]
 [ 1.78041687  3.          6.         12.        ]
 [ 1.78041687  3.          6.         12.        ]
 [ 1.78041687  3.          6.         12.        ]
 [ 3.28040348  3.          6.         12.        ]
 [ 3.28040348  3.          6.         12.        ]
 [ 3.28040348  3.          6.         12.        ]
 [ 1.21959652  3.          6.         12.        ]
 [ 1.21959652  3.          6.         12.        ]
 [ 1.21959652  3.          6.         12.        ]]

mean of base data: 
 [ 2.25

## Scenario 4
### Base Dataset

In [79]:
X_base = np.asarray([[ 2    , 2  , 4 ,  8],
                     [ 2    , 2  , 4 ,  8],
                     [ 2    , 2  , 4 ,  8],
                     [ 1    , 2  , 4 ,  8],
                     [ 1    , 2  , 4 ,  8],
                     [ 1    , 2  , 4 ,  8],
                     [ 4    , 4  , 8 ,  16],
                     [ 4    , 4  , 8 ,  16],
                     [ 4    , 4  , 8 ,  16],
                     [ 2    , 4  , 8 ,  16],
                     [ 2    , 4  , 8 ,  16],
                     [ 2    , 4  , 8 ,  16]])

############################# site ####################################

sites = np.asarray([2,2,2,2,2,2,1,1,1,1,1,1]).reshape(-1,1)

############################# age #####################################

ages = np.asarray([1,1,1,1,1,1,2,2,2,2,2,2]).reshape(-1,1)

############################# sex #####################################

sex = np.asarray([2,2,2,2,2,2,1,1,1,1,1,1]).reshape(-1,1)

#######################################################################
site_age_sex = np.concatenate((sites, ages, sex),axis=1)
print("Base dataset:\n feat1 feat2 feat3 feat4 site ages sex \n", np.concatenate((X_base, site_age_sex),axis=1))

# Creating model
model = CombatModel()
# Fitting the model and transforming the training set
X_train_harmonized = model.fit_transform(X_base, sites, sex, ages)
print("\nHarmonized: \n", X_train_harmonized)

# mean along the axis = 1  
print("\nmean of base data: \n", np.mean(X_base, axis = 0)) 
print("mean of base data, 0 - 4 : \n", np.mean(X_base[:5], axis = 0)) 
print("mean of base data, 5 - 9 : \n", np.mean(X_base[5:], axis = 0)) 
# mean along the axis = 1  
print("mean of harmonized data: \n", np.mean(X_train_harmonized, axis = 0))
print("mean of harmonized data: \n", np.mean(X_train_harmonized[0:5], axis = 0))
print("mean of harmonized data: \n", np.mean(X_train_harmonized[5:10], axis = 0))

Base dataset:
 feat1 feat2 feat3 feat4 site ages sex 
 [[ 2  2  4  8  2  1  2]
 [ 2  2  4  8  2  1  2]
 [ 2  2  4  8  2  1  2]
 [ 1  2  4  8  2  1  2]
 [ 1  2  4  8  2  1  2]
 [ 1  2  4  8  2  1  2]
 [ 4  4  8 16  1  2  1]
 [ 4  4  8 16  1  2  1]
 [ 4  4  8 16  1  2  1]
 [ 2  4  8 16  1  2  1]
 [ 2  4  8 16  1  2  1]
 [ 2  4  8 16  1  2  1]]


LinAlgError: Singular matrix